server:
  port: 9000
  servlet:
    context-path: /pay
    encoding:
      enabled: true
      charset: utf-8
      force: true

spring:
  thymeleaf:
    cache: false
  application:
    name: micr-pay
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  redis:
    host: 192.168.212.128
    port: 6379

dubbo:
  registry:
    address: zookeeper://192.168.212.128:2181
    timeout: 10000
  scan:
    base-packages: com.zcx.pay
  consumer:
    check: false
    timeout: 5000
    retries: 0